# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee061e951e4dd66a976ffada8cde20b411662eb300c9b56e8f92bb85eaa977bd9f2cf740b2d55155b9dc1aba350175bb5dac2f481ff97bf4fd595d846b20c4ae

test:
  secret_key_base: b805f928eb37d3e1ac294b1745c75f254a2e0a55d52cb1f7c1829c6279c49226c8804f0769368e71dae90a56d65c179be65eb257852266e1dc10c534c53d9e21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
